@host = http://localhost:5678

###login
POST {{host}}/user/login

{"username":"admin","password":"111111"}

###resetPassword
POST {{host}}/user/resetpass

{"oldpass":"111111","newpass":"111111"}

###register
POST {{host}}/user/register

{"username":"admin","password":"111111"}

###userLike
GET {{host}}/user/like?queryString=a


###upload
POST {{host}}/file/upload?folderId=4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryL3uJ3c0mfMKL94BR

------WebKitFormBoundaryL3uJ3c0mfMKL94BR
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: application/octet-stream

< test.png
------WebKitFormBoundaryL3uJ3c0mfMKL94BR--

###checkLibraryName false
GET {{host}}/library/check?name=Default Library


###checkLibraryName true
GET {{host}}/library/check?name=test
