definitions:
  controller.HttpResult:
    properties:
      code:
        $ref: '#/definitions/controller.MessageCode'
      data: {}
      message:
        type: string
    type: object
  controller.LoginForm:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controller.LoginInfo:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/model.User'
    type: object
  controller.MessageCode:
    enum:
    - 0
    - 1
    - 2
    - 101
    type: integer
    x-enum-varnames:
    - SUCCESS
    - FAILED
    - PARAM_ERROR
    - LOGIN_FAILED
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.Folder:
    properties:
      createdAt:
        type: string
      deleteAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      libraryID:
        type: integer
      name:
        type: string
      parentID:
        type: integer
      updatedAt:
        type: string
    type: object
  model.Library:
    properties:
      createdAt:
        type: string
      deleteAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      owner:
        $ref: '#/definitions/model.User'
      rootFolder:
        $ref: '#/definitions/model.Folder'
      updatedAt:
        type: string
    type: object
  model.LibraryRole:
    enum:
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - Read
    - Write
  model.ShareLibrary:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      library:
        $ref: '#/definitions/model.Library'
      libraryId:
        type: integer
      role:
        $ref: '#/definitions/model.LibraryRole'
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  model.User:
    properties:
      admin:
        type: boolean
      createdAt:
        type: string
      deleteAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      librarys:
        items:
          $ref: '#/definitions/model.Library'
        type: array
      password:
        type: string
      shareLibrarys:
        items:
          $ref: '#/definitions/model.ShareLibrary'
        type: array
      updatedAt:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户名密码
        in: body
        name: loginForm
        required: true
        schema:
          $ref: '#/definitions/controller.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            $ref: '#/definitions/controller.LoginInfo'
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/controller.HttpResult'
        "401":
          description: 用户名或密码错误
          schema:
            $ref: '#/definitions/controller.HttpResult'
      summary: 用户登录
      tags:
      - 用户
swagger: "2.0"
